#ifndef EVENTAPPSHARED_GLOBAL_H
#define EVENTAPPSHARED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EVENTAPPSHARED_LIBRARY)
#  define EVENTAPPSHAREDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EVENTAPPSHAREDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EVENTAPPSHARED_GLOBAL_H
